### ISSUE TITLE
How do I align center of the screen.

### ISSUE THREAD

**Issue by simneshv** [jh3y/whirl#15]
by default it is aligned center of the page. how do I change that to center of the screen.

**Comment by jh3y** [comment]
Hey @simneshv 👋 

Sorry, I've only just seen this. So you want the loading spinner to always be in the center of the screen?

One quick win here would be to change the rule on the `:after` pseudo element to use `position: fixed` and that should mean that it sits relative to the viewport at all times.

Maybe try this rule in your CSS;
```css
.whirl:after { position: fixed; }
```
It should give the desired effect :tada:

Hope that helps! 😄

**Comment by simneshv** [comment]
Thank you very much.  it works.
